# Generated by Django 5.1.3 on 2024-12-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_name_teacher_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
