# Generated by Django 5.1.3 on 2024-12-04 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='created_by',
        ),
    ]
