# Generated by Django 5.1.3 on 2024-12-04 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_user_student_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='student_name',
        ),
    ]
