# Generated by Django 5.1.3 on 2024-12-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_class_enrolled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_enrolled',
        ),
    ]
