# Generated by Django 5.1.3 on 2024-12-06 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_remove_teacher_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_code', models.CharField(max_length=10, unique=True)),
                ('sub_name', models.CharField(max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
            options={
                'db_table': 'SUBJECT',
            },
        ),
    ]
